# coding: utf-8

"""
Copyright 2015 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class DiscoveredNeighbor(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        DiscoveredNeighbor - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'heard_count': 'int',
            'mac_address': 'str',
            'rssi': 'int'
        }

        self.attribute_map = {
            'heard_count': 'heardCount',
            'mac_address': 'macAddress',
            'rssi': 'rssi'
        }

        self._heard_count = None
        self._mac_address = None
        self._rssi = None

    @property
    def heard_count(self):
        """
        Gets the heard_count of this DiscoveredNeighbor.
        Number of times the device was heard during the last HR interval

        :return: The heard_count of this DiscoveredNeighbor.
        :rtype: int
        """
        return self._heard_count

    @heard_count.setter
    def heard_count(self, heard_count):
        """
        Sets the heard_count of this DiscoveredNeighbor.
        Number of times the device was heard during the last HR interval

        :param heard_count: The heard_count of this DiscoveredNeighbor.
        :type: int
        """
        self._heard_count = heard_count

    @property
    def mac_address(self):
        """
        Gets the mac_address of this DiscoveredNeighbor.
        MAC address of the neighbor

        :return: The mac_address of this DiscoveredNeighbor.
        :rtype: str
        """
        return self._mac_address

    @mac_address.setter
    def mac_address(self, mac_address):
        """
        Sets the mac_address of this DiscoveredNeighbor.
        MAC address of the neighbor

        :param mac_address: The mac_address of this DiscoveredNeighbor.
        :type: str
        """
        self._mac_address = mac_address

    @property
    def rssi(self):
        """
        Gets the rssi of this DiscoveredNeighbor.
        Last reported RSSI

        :return: The rssi of this DiscoveredNeighbor.
        :rtype: int
        """
        return self._rssi

    @rssi.setter
    def rssi(self, rssi):
        """
        Sets the rssi of this DiscoveredNeighbor.
        Last reported RSSI

        :param rssi: The rssi of this DiscoveredNeighbor.
        :type: int
        """
        self._rssi = rssi

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other): 
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """ 
        Returns true if both objects are not equal
        """
        return not self == other

